version = 0.1

[default.deploy.parameters]
stack_name = "my-service"
resolve_s3 = true
s3_prefix = "my-service"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"dev\""
image_repositories = []
