AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Microservice Framework

Parameters:
  Env:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 900
    MemorySize: 256

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-bucket"
  
  # Service Gateway Function

  ServiceGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}"
      Description: Service Gateway Function
      Architectures:
        - arm64
      CodeUri: service-gateway/
      Handler: src/index.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          ENV: !Ref Env
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
        - LambdaInvokePolicy:
            FunctionName: !Ref SpecialFunction
  
  # Special Functions

  SpecialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-special-function"
      Description: Special Function
      Architectures:
        - arm64
      CodeUri: functions/special-function/
      Handler: src/index.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          ENV: !Ref Env
      # Policies:
      #   - S3CrudPolicy:
      #       BucketName: "*"
